modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory (28 is current forge version)
issueTrackerURL="https://github.com/gbl/WorldTime/issues"
[[mods]]
modId="worldtime"
version="${file.jarVersion}"
displayName="World Time"
displayURL="https://github.com/gbl/WorldTime"
logoFile="logo.png"
credits=""
authors="Giselbaer"
description='''
Display the current world time
'''

[[dependencies.worldtime]] #optional
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.worldtime]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1,)"
    ordering="NONE"
    side="CLIENT"
